### ISSUE TITLE
Empty objects disallowed

### ISSUE THREAD

**Issue by cemerick** [NathanReb/ppx_yojson#34]
This usage:

```ocaml
[%yojson {}]
```

yields `Error: Syntax error`. Likewise for any empty object within a `%yojson` block. Adding any member to the object yields an `` `Assoc `` value as expected.

**Comment by NathanReb** [comment]
OCaml does not allow this syntax (the empty record `{}`) so we can't support it as the payload of the extension still has to be valid OCaml.

If you need to insert empty objects in otherwise large json values, I would suggest you use antiquotation. Something along those lines:
```ocaml
let empty_object = `Assoc [] in
let json_value = [%yojson {some_field = [%aq empty_object]; some_other_field = ...}] in
...
```
or simply:
```ocaml
let json_value = [%yojson {some_field = [%aq `Assoc []]; some_other_field = ...}] in
...
```

Would that work for you?

**Comment by cemerick** [comment]
Ach, my bad, I should have realized that before filing this. Sorry for the noise :v:
